# Generated by Django 5.1.2 on 2024-10-30 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
    ]
