# Generated by Django 5.2 on 2025-05-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='enrolled_students',
        ),
        migrations.AddField(
            model_name='student',
            name='lectures',
            field=models.ManyToManyField(related_name='students', to='students.lecture'),
        ),
    ]
