# Generated by Django 5.2 on 2025-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_lecture_enrolled_students_student_lectures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lectures',
        ),
        migrations.AddField(
            model_name='lecture',
            name='enrolled_students',
            field=models.ManyToManyField(to='students.student'),
        ),
    ]
